# Generated by Django 4.2.2 on 2023-07-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_volunteer_skills_remove_event_volunteers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(default="Description"),
        ),
    ]
