# Generated by Django 4.2.2 on 2023-07-01 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("proof", models.FileField(null=True, upload_to="skill_proof/")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.user",
                    ),
                ),
            ],
            bases=("main.user",),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.user",
                    ),
                ),
                ("highest_qualification", models.TextField()),
                ("proof", models.FileField(upload_to="student_proof/")),
            ],
            bases=("main.user",),
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.user",
                    ),
                ),
                ("qualifications", models.TextField()),
                ("proof", models.FileField(upload_to="volunteer_proof/")),
                (
                    "skills",
                    models.ManyToManyField(related_name="volunteers", to="main.skill"),
                ),
            ],
            bases=("main.user",),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("online", models.BooleanField(default=True)),
                ("date_and_time", models.DateTimeField()),
                ("link", models.URLField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.skill"
                    ),
                ),
                (
                    "volunteers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.volunteer"
                    ),
                ),
            ],
        ),
    ]
