# Generated by Django 4.2.2 on 2023-07-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_address_student_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
