# Generated by Django 4.2.2 on 2023-07-01 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_student_isverified_volunteer_isverified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteer",
            name="skills",
        ),
        migrations.RemoveField(
            model_name="event",
            name="volunteers",
        ),
        migrations.AlterField(
            model_name="skill",
            name="proof",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="main.user",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="volunteers",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="main.volunteer"
            ),
        ),
    ]
