# Generated by Django 4.2.2 on 2023-07-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_event_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="skills",
            field=models.ManyToManyField(related_name="volunteers", to="main.skill"),
        ),
    ]
